"""empty message

Revision ID: 0bd18bf03d59
Revises: 122f854394a3
Create Date: 2019-05-15 16:03:42.283700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd18bf03d59'
down_revision = '122f854394a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('starling_webhook_secret', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.drop_column('user', 'starling_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('starling_enabled', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'starling_webhook_secret')
    # ### end Alembic commands ###
