"""empty message

Revision ID: 122f854394a3
Revises: ded740f7f4e2
Create Date: 2019-05-13 17:40:22.975915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122f854394a3'
down_revision = 'ded740f7f4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('starling_auth_code', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.drop_column('user', 'starling_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('starling_enabled', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'starling_auth_code')
    # ### end Alembic commands ###
