"""empty message

Revision ID: 72f989ae846a
Revises: 7ca3c3dd63ed
Create Date: 2019-05-17 14:38:21.233018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f989ae846a'
down_revision = '7ca3c3dd63ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starling_transaction', sa.Column('payee', sa.String(length=255), nullable=True))
    op.add_column('starling_transaction', sa.Column('transaction_type', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'starling_transaction', ['transaction_uid'])
    op.drop_column('starling_transaction', 'type')
    op.add_column('ynab_transaction', sa.Column('starling_transaction', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ynab_transaction', 'starling_transaction', ['starling_transaction'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ynab_transaction', type_='foreignkey')
    op.drop_column('ynab_transaction', 'starling_transaction')
    op.add_column('starling_transaction', sa.Column('type', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'starling_transaction', type_='unique')
    op.drop_column('starling_transaction', 'transaction_type')
    op.drop_column('starling_transaction', 'payee')
    # ### end Alembic commands ###
