"""empty message

Revision ID: 7ca3c3dd63ed
Revises: af13d1bb7a7d
Create Date: 2019-05-17 13:32:52.390414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca3c3dd63ed'
down_revision = 'af13d1bb7a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ynab_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.String(length=255), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ynab_id', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('payee_id', sa.String(length=255), nullable=True),
    sa.Column('payee_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ynab_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ynab_transaction')
    # ### end Alembic commands ###
