"""empty message

Revision ID: af13d1bb7a7d
Revises: a8420319160a
Create Date: 2019-05-16 16:19:58.744131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af13d1bb7a7d'
down_revision = 'a8420319160a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ynab_category_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ynab_category_id')
    # ### end Alembic commands ###
